project_id = "uthgmacvrhshqirhyuhy"

[functions.analyze-meal]
verify_jwt = true

[functions.coach-goals]
verify_jwt = true

[functions.describe-nutrient]
verify_jwt = true

[functions.coach-chat]
verify_jwt = true
